@BillWatch_API_HostAddress = https://localhost:7243

# @name login
POST {{BillWatch_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "devtest@billwatch.local",
  "password": "BillWatch!Dev123"
}

###

POST {{BillWatch_API_HostAddress}}/api/plaid/accounts/sync
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{}

###

POST {{BillWatch_API_HostAddress}}/api/plaid/transactions/sync
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: application/json

{}

###

GET {{BillWatch_API_HostAddress}}/api/bank-transactions?take=20
Authorization: Bearer {{login.response.body.$.accessToken}}